### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by sweetquiet** [abdullaayyad96/icp_localization#1]
Has it been developed?

**Comment by abdullaayyad96** [comment]
Dear Wang,

Apologies for the late reply. The developed algorithm is not well
optimized/structured at the moment. Thus I would not recommend using it at
this stage.

I will inform you of any developments in the future that would make it
easier to utilize.

Kind regards,
Abdulla Ayyad

**Comment by sweetquiet** [comment]
Hi , glad to receive your reply, this project has provided me with good ideas, thanks again!
